using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using BepInEx;
using BepInEx.Bootstrap;
using BepInEx.Logging;
using HarmonyLib;
using Newtonsoft.Json;
using UnityEngine;
using ValheimServerGuard.Shared;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ValheimServerGuardClient
{
    [BepInPlugin(GUID, NAME, VERSION)]
    public class ClientPlugin : BaseUnityPlugin
    {
        public const string GUID    = "com.taeguk.valheim.serverguard.client";
        public const string NAME    = "Valheim ServerGuard Client";
        public const string VERSION = "1.3.0";

        internal static ClientPlugin Instance;
        internal static ManualLogSource LogS;
        private Harmony _harmony;

        private string _sharedSecret = "";
        private List<ModManifestEntry> _cachedManifest;

        private static readonly string ConfDir    = Path.Combine(Paths.ConfigPath, "ServerGuard");
        private static readonly string ClientYaml = Path.Combine(ConfDir, "client.yaml");
        // Drop-in YAML snippet listing every plugin currently loaded on this client.
        // Generated on first run (and any time the file is missing). The user pastes
        // its contents into the server's allowed_mods.yaml.
        private static readonly string ExportYaml = Path.Combine(ConfDir, "mods_for_allowed_mods.yaml");

        private class ClientSettings
        {
            public string SharedSecret { get; set; } = "";
        }

        private void Awake()
        {
            Instance = this;
            LogS = Logger;

            EnsureConfig();

            _harmony = new Harmony(GUID);
            _harmony.PatchAll();

            // Don't enumerate Chainloader.PluginInfos yet - we may have loaded earlier
            // than other plugins in this BepInEx session (alphabetical order, dependencies),
            // so PluginInfos is incomplete *during* Awake. Defer to a coroutine that runs
            // after the chainloader has had time to finish its work.
            StartCoroutine(DeferredInit());
        }

        // Waits until BepInEx has loaded every other plugin, then builds the manifest
        // cache and writes the first-run allowed_mods export.
        //
        // BepInEx 5.x calls every plugin's Awake() back-to-back on the main thread before
        // returning control to Unity, so a single `yield return null` (one frame) is
        // already past the point where PluginInfos is complete. We add a small WaitForSeconds
        // safety margin in case a plugin's Awake itself yielded.
        private IEnumerator DeferredInit()
        {
            yield return null;
            yield return new WaitForSeconds(2f);

            BuildManifestCache();
            ExportAllowedModsSnippet();

            LogS.LogInfo($"[ServerGuard.Client] Loaded v{VERSION}. Manifest entries: {_cachedManifest?.Count ?? 0}. HMAC: {(string.IsNullOrEmpty(_sharedSecret) ? "OFF (no shared_secret configured)" : "ON")}");
        }

        // Writes a YAML snippet listing every loaded plugin in the exact format the
        // server's allowed_mods.yaml expects. Idempotent: only writes when the export
        // file is missing, so the user can delete it to refresh after adding/removing mods.
        private void ExportAllowedModsSnippet()
        {
            try
            {
                if (File.Exists(ExportYaml))
                {
                    LogS.LogInfo($"[ServerGuard.Client] Allowed-mods export already present at {ExportYaml}. Delete the file to regenerate.");
                    return;
                }

                var entries = _cachedManifest ?? new List<ModManifestEntry>();
                var sb = new StringBuilder();
                sb.AppendLine($"# ServerGuard - allowed_mods snippet generated by ServerGuard.Client v{VERSION}");
                sb.AppendLine($"# Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}Z   Mods on this client: {entries.Count}");
                sb.AppendLine("#");
                sb.AppendLine("# How to use:");
                sb.AppendLine("#   1. Open <server>/BepInEx/config/ServerGuard/conf/allowed_mods.yaml");
                sb.AppendLine("#   2. Replace the `allowed_mods:` block with the one below");
                sb.AppendLine("#      (or merge if you already have entries you want to keep).");
                sb.AppendLine("#   3. Save. The server hot-reloads within ~1 second.");
                sb.AppendLine("#");
                sb.AppendLine("# Each entry is `<GUID>|<sha256>` (GUID-keyed, hash-pinned).");
                sb.AppendLine("# To loosen, drop the `|<sha256>` suffix - the entry will then accept any hash.");
                sb.AppendLine("# To tighten further, leave it as-is - the server will require an exact DLL match.");
                sb.AppendLine("#");
                sb.AppendLine("# The companion plugin (this DLL) is intentionally listed under required_mods,");
                sb.AppendLine("# NOT allowed_mods - the server demands its presence.");
                sb.AppendLine();

                // Required: just the companion itself, hash-pinned to this client's build.
                var companion = entries.FirstOrDefault(m => string.Equals(m.Guid, GUID, StringComparison.OrdinalIgnoreCase));
                sb.AppendLine("required_mods:");
                if (companion != null && !string.IsNullOrEmpty(companion.Sha256))
                {
                    sb.AppendLine($"  - {companion.Guid}|{companion.Sha256}    # {companion.Name} v{companion.Version}");
                }
                else
                {
                    sb.AppendLine($"  - {GUID}                                                # {NAME} v{VERSION}");
                }
                sb.AppendLine();

                // Allowed: every other plugin currently loaded.
                sb.AppendLine("allowed_mods:");
                var others = entries
                    .Where(m => !string.Equals(m.Guid, GUID, StringComparison.OrdinalIgnoreCase))
                    .OrderBy(m => m.Name ?? "", StringComparer.OrdinalIgnoreCase)
                    .ToList();

                if (others.Count == 0)
                {
                    sb.AppendLine("  []");
                }
                else
                {
                    // Compute padding so the trailing comments line up nicely.
                    int maxKeyLen = 0;
                    foreach (var m in others)
                    {
                        var key = !string.IsNullOrEmpty(m.Guid) ? m.Guid : m.Name;
                        var entryWidth = (key ?? "").Length + (string.IsNullOrEmpty(m.Sha256) ? 0 : 1 + m.Sha256.Length);
                        if (entryWidth > maxKeyLen) maxKeyLen = entryWidth;
                    }

                    foreach (var m in others)
                    {
                        var keyOnly = !string.IsNullOrEmpty(m.Guid) ? m.Guid : (m.Name ?? "");
                        var entry   = string.IsNullOrEmpty(m.Sha256) ? keyOnly : $"{keyOnly}|{m.Sha256}";
                        var pad     = new string(' ', Math.Max(1, maxKeyLen - entry.Length + 2));
                        var label   = string.IsNullOrEmpty(m.Name) ? "" : $"{m.Name} v{m.Version}";
                        if (string.IsNullOrEmpty(m.Guid))
                        {
                            // Fall back to display-name match - flag it so the user can replace later.
                            sb.AppendLine($"  - {entry}{pad}# {label} (no GUID; consider replacing the key with the mod's BepInPlugin GUID)");
                        }
                        else
                        {
                            sb.AppendLine($"  - {entry}{pad}# {label}");
                        }
                    }
                }
                sb.AppendLine();

                sb.AppendLine("banned_mods: []");
                sb.AppendLine();

                Directory.CreateDirectory(ConfDir);
                File.WriteAllText(ExportYaml, sb.ToString());

                LogS.LogWarning("[ServerGuard.Client] First-run mod export written:");
                LogS.LogWarning($"[ServerGuard.Client]   {ExportYaml}");
                LogS.LogWarning($"[ServerGuard.Client]   ({entries.Count} plugins). Paste its contents into the server's allowed_mods.yaml.");
            }
            catch (Exception ex)
            {
                LogS.LogError($"[ServerGuard.Client] ExportAllowedModsSnippet failed: {ex.Message}");
            }
        }

        private void OnDestroy()
        {
            try { _harmony?.UnpatchSelf(); } catch { }
        }

        private void EnsureConfig()
        {
            try
            {
                Directory.CreateDirectory(ConfDir);

                if (!File.Exists(ClientYaml))
                {
                    var sb = new StringBuilder();
                    sb.AppendLine("# Valheim ServerGuard - Client config");
                    sb.AppendLine("# sharedSecret MUST match the server's settings.yaml `sharedSecret` value");
                    sb.AppendLine("# verbatim. The server will reject manifests whose HMAC does not match.");
                    sb.AppendLine("# Leave empty only if the server has `requireHmac: false` (insecure).");
                    sb.AppendLine("sharedSecret: \"\"");
                    File.WriteAllText(ClientYaml, sb.ToString());
                }

                var deser = new DeserializerBuilder()
                    .WithNamingConvention(CamelCaseNamingConvention.Instance)
                    .IgnoreUnmatchedProperties()
                    .Build();
                var doc = deser.Deserialize<ClientSettings>(File.ReadAllText(ClientYaml)) ?? new ClientSettings();
                _sharedSecret = doc.SharedSecret ?? "";
            }
            catch (Exception ex)
            {
                LogS.LogWarning($"[ServerGuard.Client] EnsureConfig failed: {ex.Message}");
            }
        }

        private void BuildManifestCache()
        {
            _cachedManifest = new List<ModManifestEntry>();
            try
            {
                foreach (var kv in Chainloader.PluginInfos)
                {
                    var info = kv.Value;
                    var meta = info?.Metadata;
                    string sha = "";

                    try
                    {
                        var path = info?.Location;
                        if (!string.IsNullOrEmpty(path) && File.Exists(path))
                        {
                            using (var sha256 = SHA256.Create())
                            using (var stream = File.OpenRead(path))
                            {
                                var hash = sha256.ComputeHash(stream);
                                sha = BitConverter.ToString(hash).Replace("-", "").ToLowerInvariant();
                            }
                        }
                    }
                    catch { /* hash optional */ }

                    _cachedManifest.Add(new ModManifestEntry
                    {
                        Guid    = meta?.GUID ?? "",
                        Name    = meta?.Name ?? "",
                        Version = meta?.Version?.ToString() ?? "",
                        Sha256  = sha
                    });
                }
            }
            catch (Exception ex)
            {
                LogS.LogError($"[ServerGuard.Client] BuildManifestCache failed: {ex.Message}");
            }
        }

        public string BuildManifestJson(string challenge)
        {
            // Always rebuild from Chainloader.PluginInfos at request time. By the time
            // the server has asked for a manifest the player is past the main menu, so
            // every plugin is loaded - we don't want to ship a stale 10-of-29 list that
            // happened to be visible when our Awake ran.
            BuildManifestCache();

            var manifest = new ModManifest
            {
                SchemaVersion = "1",
                Challenge     = challenge ?? "",
                TimestampUtc  = DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
                Mods          = _cachedManifest ?? new List<ModManifestEntry>()
            };
            manifest.Hmac = ModManifest.ComputeHmac(manifest.CanonicalForHmac(), _sharedSecret);
            return JsonConvert.SerializeObject(manifest);
        }

        // Patches ZNet.OnNewConnection so we can register our request-handler on the
        // peer-specific ZRpc as soon as we connect to a server.
        [HarmonyPatch(typeof(ZNet), "OnNewConnection")]
        public static class Patch_RegisterClientHandler
        {
            public static void Postfix(ZNetPeer peer)
            {
                try
                {
                    if (peer == null || peer.m_rpc == null) return;

                    // Only run on the client side. ZNet.IsServer() returns true on the
                    // dedicated server / host; we never need to register the request
                    // handler there because servers don't send manifests to themselves.
                    if (ZNet.instance != null && ZNet.instance.IsServer()) return;

                    peer.m_rpc.Register<string>("ServerGuard_RequestManifest", (rpc, challenge) =>
                    {
                        try
                        {
                            var json = ClientPlugin.Instance.BuildManifestJson(challenge);
                            rpc.Invoke("ServerGuard_Manifest", json);
                            ClientPlugin.LogS.LogInfo($"[ServerGuard.Client] Sent manifest ({json.Length} bytes, {ClientPlugin.Instance._cachedManifest?.Count ?? 0} mods).");
                        }
                        catch (Exception ex)
                        {
                            ClientPlugin.LogS.LogError($"[ServerGuard.Client] Manifest send failed: {ex.Message}");
                        }
                    });

                    ClientPlugin.LogS.LogInfo("[ServerGuard.Client] Registered manifest request handler on server peer.");
                }
                catch (Exception ex)
                {
                    ClientPlugin.LogS?.LogError($"[ServerGuard.Client] Register handler failed: {ex.Message}");
                }
            }
        }
    }
}
